/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tableproject;

import java.awt.List;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;

/**
 *
 * @author eduma
 */
public class Interfaz extends javax.swing.JFrame {

    private boolean connected = false;
    private Map<String, String[]> data = new HashMap<String, String[]>();
    private String [] nameTables;
    private DefaultListModel modeloTabla = new DefaultListModel();
    private DefaultListModel modeloCampo = new DefaultListModel();
    private JOptionPane dialog = new JOptionPane();
    
    public Interfaz() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        listaTabla.setModel(modeloTabla);
        listaCampos.setModel(modeloCampo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        ventPrincipal = new javax.swing.JDesktopPane();
        buttonLogin = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaTabla = new javax.swing.JList<>();
        labelTablas = new javax.swing.JLabel();
        labelCampos = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCampos = new javax.swing.JList<>();
        panelButton = new javax.swing.JPanel();
        labelTituloBoton = new javax.swing.JLabel();
        simpleButton = new javax.swing.JToggleButton();
        intervalButton = new javax.swing.JToggleButton();
        multipleIntButton = new javax.swing.JToggleButton();
        labelCopyFer = new javax.swing.JLabel();
        labelCopyEdu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        panelTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listaTabla.setMaximumSize(new java.awt.Dimension(150, 250));
        listaTabla.setMinimumSize(new java.awt.Dimension(150, 250));
        listaTabla.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaTablaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaTabla);

        labelTablas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTablas.setText("Tablas");

        labelCampos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCampos.setText("Campos");

        clearButton.setText("Limpiar");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listaCampos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaCampos);

        panelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTituloBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTituloBoton.setText("Tipo de selección");

        buttonGroup.add(simpleButton);
        simpleButton.setText("Simple");
        simpleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(intervalButton);
        intervalButton.setText("Por intervalo");
        intervalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervalButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(multipleIntButton);
        multipleIntButton.setText("Múltiples intervalos");
        multipleIntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleIntButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                        .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(simpleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intervalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multipleIntButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                        .addComponent(labelTituloBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addComponent(labelTituloBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simpleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(intervalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(multipleIntButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                        .addComponent(labelTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(labelCampos)
                        .addGap(83, 83, 83))))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTablas)
                            .addComponent(labelCampos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(clearButton)))
                .addContainerGap())
        );

        labelCopyFer.setText(" © Fernando Marcelo Alonso");

        labelCopyEdu.setText("  Eduardo Maldonado Fernández");

        ventPrincipal.setLayer(buttonLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ventPrincipal.setLayer(panelTabla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ventPrincipal.setLayer(labelCopyFer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ventPrincipal.setLayer(labelCopyEdu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ventPrincipalLayout = new javax.swing.GroupLayout(ventPrincipal);
        ventPrincipal.setLayout(ventPrincipalLayout);
        ventPrincipalLayout.setHorizontalGroup(
            ventPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventPrincipalLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventPrincipalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                .addComponent(labelCopyEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCopyFer, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        ventPrincipalLayout.setVerticalGroup(
            ventPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCopyFer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCopyEdu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        if(!connected){
            LoginVentana IntLogin = new LoginVentana(this);
            IntLogin.setTitle("Inicio Login");
            IntLogin.setLocation(new Point(50, 80));
            ventPrincipal.add(IntLogin);
            IntLogin.setVisible(false);
            IntLogin.setVisible(true);
        }else{
            modeloCampo.removeAllElements();
            modeloTabla.removeAllElements();
            buttonLogin.setText("Login");
            connected = false;
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void simpleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleButtonActionPerformed
        if(connected){
            listaTabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }else{
            notifyLogin();
        }
    }//GEN-LAST:event_simpleButtonActionPerformed

    private void intervalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intervalButtonActionPerformed
        if(connected){
            listaTabla.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        }else{
            notifyLogin();
        }
    }//GEN-LAST:event_intervalButtonActionPerformed

    private void multipleIntButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleIntButtonActionPerformed
        if(connected){
            listaTabla.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        }else{
            notifyLogin();
        }
         
    }//GEN-LAST:event_multipleIntButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        if(connected){
            listaTabla.clearSelection();
            listaCampos.clearSelection();
        }else{
            notifyLogin();
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    private void listaTablaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaTablaValueChanged
        modeloCampo.removeAllElements();
        int [] selected = listaTabla.getSelectedIndices();
        for(int i= 0; i < selected.length; i++){
            String [] campos = data.get(nameTables[selected[i]]);
            for(String campo : campos){
                modeloCampo.addElement(nameTables[selected[i]] + "." + campo);
            }
        }
    }//GEN-LAST:event_listaTablaValueChanged

    protected void loginSuccess() throws ClassNotFoundException, SQLException{
        buttonLogin.setText("Logout");
        connected = true;
        accessBD();
        showTablas();
        
    }
    
    private void showTablas(){
        int i = 0;
        nameTables = new String[data.size()];
        for(String nombreTabla : data.keySet()){
            nameTables[i] = nombreTabla;
            modeloTabla.addElement(nombreTabla);
            i++;
        }
    }
    
    private void notifyLogin(){
        dialog.showMessageDialog(null,"Para poder acceder a la base de datos, seleccione Login","Cuenta no conectada", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void accessBD() throws ClassNotFoundException, SQLException{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://mozart.dis.ulpgc.es/DIU_BD?useSSL=true",
            "estudiante-DIU",
            "DIU-aed56-noi");
        DatabaseMetaData md = con.getMetaData();
        String[] types = {"TABLE"};
        ResultSet rs = md.getTables(null, null, "%", types);
        while (rs.next()) {
            String nombreTabla = rs.getString("TABLE_NAME");
            System.out.println("Tabla: " + nombreTabla);
            ResultSet rs2 = md.getColumns(null, null, nombreTabla, null);
            rs2.last();
            String [] vec = new String[rs2.getRow()-1];
            rs2.first();
            int i = 0;
            while (rs2.next()) {
                String nombreCampo = rs2.getString("COLUMN_NAME");
                vec[i] = nombreCampo;
                System.out.println(" Campo: " + nombreCampo);
                i++;
            }
            data.put(nombreTabla, vec);
        }
        con.close();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton clearButton;
    private javax.swing.JToggleButton intervalButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCampos;
    private javax.swing.JLabel labelCopyEdu;
    private javax.swing.JLabel labelCopyFer;
    private javax.swing.JLabel labelTablas;
    private javax.swing.JLabel labelTituloBoton;
    private javax.swing.JList<String> listaCampos;
    private javax.swing.JList<String> listaTabla;
    private javax.swing.JToggleButton multipleIntButton;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JToggleButton simpleButton;
    private javax.swing.JDesktopPane ventPrincipal;
    // End of variables declaration//GEN-END:variables
}
